---
title: "Diagnostic Plots - Main Model with Random Slopes - Wolf et al. (2023) Informed Priors"
subtitle: "The effects of muscle length during resistance training on regional hypertrophy adaptations: A systematic review and meta-analysis"
author: "Dorian Varovic, Milo Wolf, Brad J. Schoenfeld, James Steele, Pavle Mikulic"
format:
  pdf:
    documentclass: report
    toc: false
    number-sections: false
    highlight-style: github
    fig-width: 10
    fig-height: 10
---
```{r}
#| message: false
#| warning: false
#| echo: false
#| include: false
targets::tar_config_set(store = here::here('_targets'))
```

# Standardised Mean Difference Model

## Pre-registered Main Model

### $\hat{R}$

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(rhat_wolf_priors_model_slopes_SMD)

rhat_wolf_priors_model_slopes_SMD 

```

### Trace plots

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(trace_plot_wolf_priors_model_slopes_SMD)

trace_plot_wolf_priors_model_slopes_SMD

```

### Posterior predictive check

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(pp_check_wolf_priors_model_slopes_SMD)

pp_check_wolf_priors_model_slopes_SMD

```

# Log Response Ratio Model

## Pre-registered Main Model

### $\hat{R}$

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(rhat_wolf_priors_model_slopes_lnRR)

rhat_wolf_priors_model_slopes_lnRR 

```

### Trace plots

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(trace_plot_wolf_priors_model_slopes_lnRR)

trace_plot_wolf_priors_model_slopes_lnRR

```

### Posterior predictive check

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(pp_check_wolf_priors_model_slopes_lnRR)

pp_check_wolf_priors_model_slopes_lnRR

```


